package com.novadb.exception;

/**
 * Base exception for all custom errors generated by NovaDB.
 */
public class NovaDBException extends RuntimeException {
    
    public NovaDBException(String message) {
        super(message);
    }

    public NovaDBException(String message, Throwable cause) {
        super(message, cause);
    }
}
