package com.novadb.lexer;

/**
 * Represents a token generated by the Lexer.
 * 
 * @param type The classification of the token.
 * @param lexeme The raw characters matching the token in the source query.
 * @param literal The parsed native Java object value for literal values (like numbers or strings).
 * @param position Character index offset from the start of the query string.
 */
public record Token(TokenType type, String lexeme, Object literal, int position) {
    @Override
    public String toString() {
        return String.format("Token(%s, '%s', %s, @%d)", type, lexeme, literal, position);
    }
}
